name: surtmio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0" # Corregido para usar un rango de versiones compatible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Agregado para generar íconos

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons: # Configuración para generar íconos
  android: "launcher_icon" # Nombre del ícono para Android
  ios: true # Habilita la generación del ícono para iOS
  image_path: "assets/icon.png" # Ruta de tu archivo de ícono
