// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPR8NBJM-eptSFa7gTiRc_twP-GQSPRm0',
    appId: '1:1020410653787:web:8aae3d43381c311251a37e',
    messagingSenderId: '1020410653787',
    projectId: 'surtmio',
    authDomain: 'surtmio.firebaseapp.com',
    storageBucket: 'surtmio.firebasestorage.app',
    measurementId: 'G-731C1HNKYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlixK0fGEWM5sNfrrTnSqRu1UQHJC8B0',
    appId: '1:1020410653787:android:355306173cec9fcd51a37e',
    messagingSenderId: '1020410653787',
    projectId: 'surtmio',
    storageBucket: 'surtmio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9H7RjQOJiUZky4qglU02wsXebwkn9RU',
    appId: '1:1020410653787:ios:45720a5f0a638b1b51a37e',
    messagingSenderId: '1020410653787',
    projectId: 'surtmio',
    storageBucket: 'surtmio.firebasestorage.app',
    iosBundleId: 'com.example.surtmio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn9H7RjQOJiUZky4qglU02wsXebwkn9RU',
    appId: '1:1020410653787:ios:45720a5f0a638b1b51a37e',
    messagingSenderId: '1020410653787',
    projectId: 'surtmio',
    storageBucket: 'surtmio.firebasestorage.app',
    iosBundleId: 'com.example.surtmio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPR8NBJM-eptSFa7gTiRc_twP-GQSPRm0',
    appId: '1:1020410653787:web:aa4d15d1e122ce6551a37e',
    messagingSenderId: '1020410653787',
    projectId: 'surtmio',
    authDomain: 'surtmio.firebaseapp.com',
    storageBucket: 'surtmio.firebasestorage.app',
    measurementId: 'G-F22J0EXJ5F',
  );
}
